spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/porhincak/argo-test
    repoURLValues: https://github.com/porhincak/argo-test
    targetRevision: HEAD
