volumes:
  - name: admin-assets
    size: "2Gi"
  - name: admin-accounting
    size: "2Gi"
  - name: cart-api-invoices
    size: "2Gi"
  - name: flower-taskdb
    size: "20Gi"
  - name: frm-hu-invoices
    size: "1Gi"
  - name: frm-tmp
    size: "1Gi"
  - name: frm-eszigno3
    size: "1Gi"
  - name: frm-var-log
    size: "1Gi"
  - name: notification-uploads
    size: "8Gi"
  - name: wp-blog-uploads
    size: "10Gi"
  - name: wp-blog-languages
    size: "2Gi"
  - name: wp-blog-cache
    size: "2Gi"
  - name: wp-blog-redis-data
    size: "2Gi"
  - name: wp-cary-uploads
    size: "8Gi"
  - name: wp-cary-languages
    size: "2Gi"
  - name: wp-cary-cache
    size: "2Gi"
  - name: wp-generic-uploads
    size: "8Gi"
  - name: wp-generic-languages
    size: "2Gi"
  - name: wp-generic-cache
    size: "2Gi"
  - name: ws-web-subdomains-data
    size: "8Gi"
  - name: ws-web-subdomains-data-hu
    size: "4Gi"
  - name: ws-cdn-ws-cdn
    size: "16Gi" # Exists on staging, but stack that uses it isn't present. Probably just for FTP stack(?)
  - name: wp-knowledgebase-uploads
    size: "8Gi"
  - name: wp-knowledgebase-cache
    size: "2Gi"
  - name: wp-knowledgebase-languages
    size: "2Gi"
  - name: wp-knowledgebase-redis-data
    size: "2Gi"
  - name: busybox-test-1
    size: "1Gi"
  - name: busybox-test-2
    size: "1Gi"